apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: app
spec:
  type: ExternalName
  ports:
    - port: 5432
      targetPort: 5432
  externalName: {{ .Values.externalServices.postgresServiceFQDN }}
