apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: result
  ports:
    - port: {{ .Values.result.port }}
      targetPort: {{ .Values.result.targetPort }}