apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: vote
  ports:
    - port: {{ .Values.vote.port }}
      targetPort: {{ .Values.vote.port }}