apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/audit: "baseline"
    pod-security.kubernetes.io/warn: "baseline"
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    name: db
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/audit: "baseline"
    pod-security.kubernetes.io/warn: "baseline"
