name: Build and deploy an app to AKS with Helm

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "tactfulvotingappacr"
  RESOURCE_GROUP: "voting-app-rg"
  CLUSTER_NAME: "voting-app-aks"
  CHART_PATH: "charts/voting-app/"
  CHART_OVERRIDE_PATH: "charts/voting-app/"
  TAG: "latest"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: üîë Azure Login via az cli
        shell: bash
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          echo "Logging into Azure using Service Principal..."
          az login --service-principal \
            -u $AZURE_CLIENT_ID \
            -p $AZURE_CLIENT_SECRET \
            --tenant $AZURE_TENANT_ID \
            --output none
            
          echo "Setting default subscription..."
          az account set --subscription $AZURE_SUBSCRIPTION_ID

      # Builds and pushes an image up to your Azure Container Registry
      - name: üèóÔ∏è Build & Push Vote App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: /docker/vote/Dockerfile
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/voteimage:${{ env.TAG }}

      # Build and Push 'worker' (Python Worker)
      - name: üèóÔ∏è Build & Push Worker App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/worker/Dockerfile
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/workerimage:${{ env.TAG }}

      # Build and Push 'result' (Node.js App)
      - name: üèóÔ∏è Build & Push Result App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/result/Dockerfile
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/resultimage:${{ env.TAG }}
          
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [buildImage]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      # Runs Helm to create manifest files
      - name: Bake deployment
        uses: azure/k8s-bake@v2
        with:
          renderEngine: "helm"
          helmChart: ${{ env.CHART_PATH }}
          overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
          overrides: |
            replicas:2
          helm-version: "latest"
        id: bake

      # Deploys application based on manifest files from previous step
      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
